"""add lessons learned models

Revision ID: 4c67c616db20
Revises: 9804c2247912
Create Date: 2024-09-06 11:41:29.084419

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4c67c616db20"
down_revision: Union[str, None] = "9804c2247912"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lessons_learned",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.Uuid(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sent", sa.DateTime(), nullable=False),
        sa.Column("submitted", sa.DateTime(), nullable=False),
        sa.Column("reason_other", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("service_quality", sa.Integer(), nullable=False),
        sa.Column("responsiveness", sa.Integer(), nullable=False),
        sa.Column("reliability", sa.Integer(), nullable=False),
        sa.Column("ease_of_use", sa.Integer(), nullable=False),
        sa.Column("benefits", sa.TEXT(), nullable=True),
        sa.Column("suggestions", sa.TEXT(), nullable=True),
        sa.Column("challenges", sa.TEXT(), nullable=True),
        sa.Column("how_evo_beneficial", sa.TEXT(), nullable=True),
        sa.Column("likely_to_reccommend", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lessons_learned_is_deleted"), "lessons_learned", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_experiments_lego_evo_lead"), "experiments", ["lego_evo_lead"], unique=False
    )
    op.create_index(
        op.f("ix_experiments_lego_evo_second"), "experiments", ["lego_evo_second"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "experiments", type_="foreignkey")
    op.drop_constraint(None, "experiments", type_="foreignkey")
    op.drop_index(op.f("ix_experiments_lego_evo_second"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_lego_evo_lead"), table_name="experiments")
    op.drop_index(op.f("ix_lessons_learned_is_deleted"), table_name="lessons_learned")
    op.drop_table("lessons_learned")
    # ### end Alembic commands ###
