"""Add more tables

Revision ID: d2becf46c89a
Revises: 3ada70c60680
Create Date: 2024-09-02 17:36:52.589460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2becf46c89a'
down_revision: Union[str, None] = '3ada70c60680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_short', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_providers_is_deleted'), 'cloud_providers', ['is_deleted'], unique=False)
    op.create_table('users_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_roles_is_deleted'), 'users_roles', ['is_deleted'], unique=False)
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_index(op.f('ix_users_roles_is_deleted'), table_name='users_roles')
    op.drop_table('users_roles')
    op.drop_index(op.f('ix_cloud_providers_is_deleted'), table_name='cloud_providers')
    op.drop_table('cloud_providers')
    # ### end Alembic commands ###
