# Generated by Django 5.1 on 2024-08-26 18:17

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('name_long', models.CharField(max_length=200)),
                ('status', models.CharField(choices=crm.models.Experiment.Status, default='new', max_length=20)),
            ],
        ),
    ]
